name: Keploy API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Match your local Python version

    - name: Set up virtual environment and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Install Keploy with error check
      run: |
        curl -fsSL https://github.com/keploy/keploy/releases/latest/download/install.sh -o install.sh
        bash install.sh

    - name: Run Keploy Tests
      run: |
        keploy test -c "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
