- name: Install Keploy CLI
  run: |
    curl --silent -L https://keploy.io/ent/install.sh | bash

    - name: Run Keploy Test Suite
  run: |
    export KEPLOY_API_KEY=SG5XMplTdz6BiitBOw== && keploy test-suite --app=7ce3dd8a-22a6-4561-a8c3-c38144f3920a --base-path https://petclinic-hosted.keploy.io/6819a98767b4adbee7b4c26c/api/ --cloud