name: Keploy CI API Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  keploy-api-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install app dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Install Keploy CLI
      run: |
        curl -fsSL https://keploy.io/install.sh -o install.sh
        source install.sh

    - name: Run Keploy tests
      run: |
        keploy test -c "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000" --delay 10

    - name: Upload Keploy Reports (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: keploy-report
        path: keploy/reports
