name: Keploy CI API Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  keploy-api-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install app dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Install Keploy CLI
      run: |
        curl --silent -L https://keploy.io/ent/install.sh | bash

    - name: Run Keploy Cloud Test Suite
      run: |
        export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
        keploy test-suite --app=7ce3dd8a-22a6-4561-a8c3-c38144f3920a --base-path https://petclinic-hosted.keploy.io/6819a98767b4adbee7b4c26c/api/ --cloud

          - name: Run Keploy Test Suite
  run: |
    export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
    keploy test-suite --app=03d24177-315c-4ee1-a3ac-64ed0ab38567 --base-path http://localhost:8080/books --cloud

    - name: Upload Keploy Reports (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: keploy-report
        path: keploy/reports
